/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H
enum arch_invocation_label {
    RISCVPageTableMap = nSeL4ArchInvocationLabels,
    RISCVPageTableUnmap,
    RISCVLVL2PageTableMap,
    RISCVLVL2PageTableUnmap,
    RISCVPageMap,
    RISCVPageUnmap,
    RISCVPageClean_Data,
    RISCVPageGetAddress,
    RISCVASIDControlMakePool,
    RISCVASIDPoolAssign,
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
